- name: create working_dir directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ image_dir }}"

- block:
  - name: download image
    copy: src={{ project_dir }}/packages/middle_img/{{ container_image }} dest={{ image_dir }}/{{ container_image }} mode=0644

  - name: load image
    shell: /usr/bin/docker load -i {{ image_dir }}/{{ container_image }}
    ignore_errors: true

  when: "MID_INSTALL_SOURCE == 'offline'"

- name: remove container
  docker_container:
    name: "{{ container_name }}"
    state: absent

- name: create container
  docker_container:
    name: "{{ container_name }}"
    image: "obsidiandynamics/{{ container_image }}"
    pull: "{{ pull }}"
    env:
      KAFKA_BROKERCONNECT: "{{ kafka_ip }}:{{ kafka_port }}"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    ports:
     - "{{ kafdrop_port }}:9000"                              #端口映射
    state: started                              #启动
    restart_policy: always