- name: 获取是否已经安装docker
  shell: 'systemctl is-active docker || echo "NoFound"'
  register: docker_svc

- name: 获取docker版本信息
  shell: "{{ project_dir }}/packages/binary_tag/bin/dockerd --version|cut -d' ' -f3"
  register: docker_ver
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: debug info
  debug: var="docker_ver"
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: 转换docker版本信息为浮点数
  set_fact: 
    DOCKER_VER: "{{ docker_ver.stdout.split('.')[0]|int + docker_ver.stdout.split('.')[1]|int/100 }}"
  connection: local
  run_once: true
  tags: upgrade_docker, download_docker

- name: debug info
  debug: var="DOCKER_VER"
  tags: upgrade_docker, download_docker

- block:
    - name: 准备docker相关目录
      file: name={{ item }} state=directory
      with_items:
      - "{{ bin_dir }}"
      - "/etc/docker"
      - "/etc/bash_completion.d"
 
    - name: 下载 docker 二进制文件(>= 18.09.x)
      copy: src={{ project_dir }}/packages/binary_tag/bin/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
      with_items:
      - docker-compose
      - containerd
      - containerd-shim-runc-v2
      - ctr
      - docker
      - dockerd
      - docker-init
      - docker-proxy
      - runc
    
    - name: docker命令自动补全
      copy: src=docker dest=/etc/bash_completion.d/docker mode=0644
    
    - name: docker国内镜像加速
      template: src=daemon.json.j2 dest=/etc/docker/daemon.json
    
    - name: flush-iptables
      shell: "source /etc/profile; iptables -P INPUT ACCEPT \
            && iptables -P FORWARD ACCEPT \
            && iptables -P OUTPUT ACCEPT \
            && iptables -F && iptables -X \
            && iptables -F -t nat && iptables -X -t nat \
            && iptables -F -t raw && iptables -X -t raw \
            && iptables -F -t mangle && iptables -X -t mangle"
    
    - name: 创建docker的systemd unit文件
      template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
      tags: upgrade_docker, download_docker
    
    - name: 开机启用docker 服务
      shell: systemctl enable docker
      ignore_errors: true
    
    - name: 开启docker 服务
      shell: systemctl daemon-reload && systemctl restart docker
      tags: upgrade_docker

    - name: 轮询等待docker服务运行
      shell: "systemctl is-active docker.service"
      register: docker_status
      until: '"active" in docker_status.stdout'
      retries: 8
      delay: 2
      tags: upgrade_docker
    
    # 配置 docker 命令软链接，方便单独安装 docker
    - name: 配置 docker 命令软链接
      file: src={{ bin_dir }}/docker dest=/usr/bin/docker state=link
      ignore_errors: true

    - name: 配置 docker-compose 命令软链接
      file: src={{ bin_dir }}/docker-compose dest=/usr/bin/docker-compose state=link
      ignore_errors: true
  when: "'NoFound' in docker_svc.stdout"

# 使支持 docker_container 模块
# - include: pip-docker.yml