# calculate filesystem used and free percent
# elasticsearch_filesystem_data_used_percent = 100 * (elasticsearch_filesystem_data_size_bytes - elasticsearch_filesystem_data_free_bytes) / elasticsearch_filesystem_data_size_bytes
# elasticsearch_filesystem_data_free_percent = 100 - elasticsearch_filesystem_data_used_percent
groups:

- name: Elasticsearch
  rules:
  - alert: "ElasticsearchTooFewNodesRunning"
    expr: elasticsearch_cluster_health_number_of_nodes < 3
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Elasticsearch running on less than 3 nodes"
      description: "There are only {{$value}} < 3 Elasticsearch nodes running"

  - alert: "ElasticsearchHeapTooHigh"
    expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"} > 0.9
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: "The heap usage is over 90% for 15m"
      description: "Elasticsearch node {{$labels.node}} heap usage is high"