

- name: download flume tag
  unarchive:
    src: "{{ project_dir }}/packages/binary_tag/apache-flume-1.7.0.zip"
    dest: /data
    creates: /data/apache-flume-1.7.0

- name: 配置 flume 软链接
  file: 
    src: "/data/apache-flume-1.7.0"
    dest: "{{ flume_home }}"
    state: link
    force: yes
  ignore_errors: true

- name: add java home
  shell: "echo JAVA_HOME={{ java_home }} >> /etc/environment"

- name: 添加执行权限
  shell: "chmod +x bin/flume-ng"
  args:
    chdir: "{{ flume_home }}"

- name: Template kafka-flume-hdfs.template file to conf
  template:
    src: kafka-flume-hdfs.conf.j2
    dest: "{{ flume_home }}/conf/kafka-flume-hdfs.conf"
    mode: '0644'

- name: start kafka-flume-hdfs
  shell: nohup bin/flume-ng agent --conf-file conf/kafka-flume-hdfs.conf -Xmx1024m -Xmx1024m --name a1 -Dflume.root.logger=INFO,LOGFILE >logs/kafka-flume-hdfs.log 2>&1 &
  args:
    chdir: "{{ flume_home }}"

- name: Template rocket-flume-session.template file to conf
  template:
    src: rocket-flume-session.conf.j2
    dest: "{{ flume_home }}/conf/rocket-flume-session.conf"
    mode: '0644'

- name: start rocket-flume-session
  shell: nohup bin/flume-ng agent --conf-file conf/rocket-flume-session.conf -Xms1024m -Xmx1024m --name a3 -Dflume.root.logger=INFO,LOGFILE >logs/rocket-flume-session.log 2>&1 &
  args:
    chdir: "{{ flume_home }}"

- name: crontab job
  cron:
    name: "add data"
    minute: "*/30"
    job: "echo 1 >> {{ flume_home }}/add_partition.txt"