- name: create working_dir directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ working_dir }}"
    - "{{ image_dir }}"

- block:
  - name: download image
    copy: src={{ project_dir }}/packages/middle_img/{{ container_image }} dest={{ image_dir }}/{{ container_image }} mode=0644

  - name: load image
    shell: /usr/bin/docker load -i {{ image_dir }}/{{ container_image }}
    ignore_errors: true

  when: "MID_INSTALL_SOURCE == 'offline'"

- name: copy docker-compose-kuboard.yml.j2 file
  template: src=docker-compose-kuboard.yml.j2 dest={{ working_dir }}/docker-compose-kuboard.yml mode=0755

- name: remove container  
  shell: docker-compose -f docker-compose-kuboard.yml down
  args:
    chdir: "{{ working_dir }}"

- name: create container  {{ container_name }}
  shell: docker-compose -f docker-compose-kuboard.yml up -d
  args:
    chdir: "{{ working_dir }}"