- name: create working_dir directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ working_dir }}"
    - "{{ image_dir }}"

- name: create data directory
  file:
    path: "{{ working_dir }}/data"
    state: directory
    owner: 1001
    group: 1001

- block:
  - name: download image
    copy: src={{ project_dir }}/packages/middle_img/{{ container_file }} dest={{ image_dir }}/{{ container_file }} mode=0644

  - name: load image
    shell: /usr/bin/docker load -i {{ image_dir }}/{{ container_file }}
    ignore_errors: true

  when: "MID_INSTALL_SOURCE == 'offline'"

- name: copy docker-compose-redis_master.yml file
  template: src=docker-compose-redis_master.yml.j2 dest={{ working_dir }}/docker-compose-redis_master.yml mode=0755
  when: "container_name == 'redis-master'"

- name: copy docker-compose-redis_slave.yml file
  template: src=docker-compose-redis_slave.yml.j2 dest={{ working_dir }}/docker-compose-redis_slave.yml mode=0755
  when: "container_name == 'redis-slave'"

- name: remove container  redis_master
  shell: docker-compose -f docker-compose-redis_master.yml down
  args:
    chdir: "{{ working_dir }}"
  when: "container_name == 'redis-master'"

- name: create container  {{ container_name }}
  shell: docker-compose -f docker-compose-redis_master.yml up -d
  args:
    chdir: "{{ working_dir }}"
  when: "container_name == 'redis-master'"

- name: remove container  redis_slave
  shell: docker-compose -f docker-compose-redis_slave.yml down
  args:
    chdir: "{{ working_dir }}"
  when: "container_name == 'redis-slave'"

- name: create container  {{ container_name }}
  shell: docker-compose -f docker-compose-redis_slave.yml up -d
  args:
    chdir: "{{ working_dir }}"
  when: "container_name == 'redis-slave'"