# 系统基础软件环境
- import_tasks: centos.yml
  # when: 'ansible_distribution in ["CentOS","RedHat","Amazon","Aliyun"]' 

# 公共系统参数设置
- import_tasks: common.yml

- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - /opt/kube/images

# 某些系统没有/usr/bin/python，需要配置一个软链接，否则connection: local的任务会失败
# 如果仍旧出现任务失败，重新执行一遍即可 https://github.com/ansible/ansible/issues/64903
- name: symlink /usr/bin/python -> /usr/bin/python3
  raw: |
    if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
      ln --symbolic /usr/bin/python3 /usr/bin/python;
    fi

# 重启服务器
# - name: Reboot a slow machine that might have lots of updates to apply
#   reboot:
#     reboot_timeout: 3600