fastdfs_image: fastdfs-nginx:V6.07

tracker_name: tracker
storage_name: storage

# tracker_list: "{{ groups.fastdfs|join(',') }}"
tracker_ip: "{{ groups.fastdfs[0] }}"

pull: "{%- if MID_INSTALL_SOURCE == 'offline' -%} \
          no \
      {%- else -%} \
          yes \
      {%- endif -%}"