
- name: download blackbox_exporter tag
  unarchive:
    src: "{{ project_dir }}/packages/binary_tag/monitor/{{ blackbox_package }}"
    dest: "{{ data_root_dir }}"
    creates: "{{ data_root_dir }}/{{ blackbox_package.split('.t')[0] }}"

- name: 配置 blackbox_exporter 软链接
  file: 
    src: "{{ data_root_dir }}/{{ blackbox_package.split('.t')[0] }}"
    dest: "{{ blackbox_dir }}"
    state: link
    force: yes
  ignore_errors: true

- name: Template blackbox_exporter systemd service file
  template:
    src: blackbox_exporter.service.j2
    dest: "{{ blackbox_unit_path }}"
    mode: 0644

- name: Start the blackbox_exporter service
  systemd:
    name: blackbox_exporter.service
    state: started
    enabled: yes