- name: Create prometheus group
  group:
    name: "{{ prometheus_group }}"
    state: present
    system: yes
  when: prometheus_create_user_group | bool
  tags:
    - prometheus_group

- name: Create prometheus user
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    state: present
    createhome: no
    system: yes
  when: prometheus_create_user_group | bool
  tags:
    - prometheus_user

- name: download prometheus tag
  unarchive:
    src: "{{ project_dir }}/packages/binary_tag/monitor/{{ prometheus_package }}"
    dest: "{{ data_root_dir }}"
    group: "{{ prometheus_group }}"
    owner: "{{ prometheus_user }}"
    creates: "{{ data_root_dir }}/{{ prometheus_package.split('.t')[0] }}"


- name: 配置 prometheus 软链接
  file: 
    src: "{{ data_root_dir }}/{{ prometheus_package.split('.t')[0] }}"
    dest: "{{ prometheus_dir }}"
    state: link
    force: yes
  ignore_errors: true

- name: Create directory for data
  file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    group: "{{ prometheus_group }}"
    owner: "{{ prometheus_user }}"
    mode: 0755

- name: copy directory for configs
  copy:
    src: configs
    dest: "{{ prometheus_dir }}"
    group: "{{ prometheus_group }}"
    owner: "{{ prometheus_user }}"
    mode: 0644

- name: copy directory for rules
  copy:
    src: rules
    dest: "{{ prometheus_dir }}"
    group: "{{ prometheus_group }}"
    owner: "{{ prometheus_user }}"
    mode: 0644
  when: server_enabled | bool

- name: Template configuration file to prometheus.yml
  template:
    src: "{{ prometheus_conf }}"
    dest: "{{ prometheus_dir }}/prometheus.yml"
    group: "{{ prometheus_group }}"
    owner: "{{ prometheus_user }}"
    mode: 0644
  notify:
    - Restart Prometheus service

- name: Template prometheus systemd service file
  template:
    src: "{{ prometheus_service }}"
    dest: "{{ prometheus_unit_path }}"
    group: "{{ prometheus_group }}"
    owner: "{{ prometheus_user }}"
    mode: 0644

- name: Start the prometheus service
  systemd:
    name: prometheus.service
    state: started
    enabled: yes

- name: download nacos-check tag
  unarchive:
    src: "nacos-check_Linux_x86_64.tar.gz"
    dest: /opt
    mode: 0755

- name: run nacos-check
  shell: "nohup ./nacos-check web --url http://{{ nacos_url }} --lable project={{ project }} --password={{ nacos_pw }} >/dev/null 2>&1 &"
  args:
    chdir: /opt
  when: nacos_enabled | bool