# 镜像名称
container_name: "{%- if inventory_hostname == groups.mysql[0] -%} \
                    mysql-master \
                {%- else -%} \
                    mysql-slave \
                {%- endif -%}"
container_file: "mysql_{{ container_tag }}"
container_image: "mysql:{{ container_tag }}"

pull: "{%- if MID_INSTALL_SOURCE == 'offline' -%} \
          no \
      {%- else -%} \
          yes \
      {%- endif -%}"

master_ip: "{{ groups.mysql[0] }}"
slave_ip: "{{ groups.mysql[1] }}"
