---
# Installation variables

prometheus_create_user_group: true
prometheus_group: prometheus
prometheus_user: prometheus

data_root_dir: /data
prometheus_dir: "{{ data_root_dir }}/prometheus"
blackbox_dir: "{{ data_root_dir }}/blackbox_exporter"
alertmanager_dir: "{{ data_root_dir }}/alertmanager"
elasticsearch_dir: "{{ data_root_dir }}/elasticsearch_exporter"

prometheus_data_dir: "{{ prometheus_dir }}/data"
prometheus_conf: "prometheus.yml.j2"
prometheus_service: "prometheus.service.j2"

prometheus_unit_path: /etc/systemd/system/prometheus.service
blackbox_unit_path: /etc/systemd/system/blackbox_exporter.service
alertmanager_unit_path: /etc/systemd/system/alertmanager.service
elasticsearch_unit_path: /etc/systemd/system/elasticsearch_exporter.service

prometheus_version: 2.37.6
prometheus_package: prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
blackbox_package: blackbox_exporter-0.23.0.linux-amd64.tar.gz
alertmanager_package: alertmanager-0.25.0.linux-amd64.tar.gz
elasticsearch_package: elasticsearch_exporter-1.5.0.linux-amd64.tar.gz

grafana_rpm: grafana-9.4.3-1.x86_64.rpm

local_ip: "{{ inventory_hostname }}"
sop_key: "0db98741-626f-4d07-8ef9-bd900eca5cdd"

es_ip: "{{ groups.es[0] }}"