# 镜像名称
container_name: "mysql"
container_file: "mysql_{{ container_tag }}"
container_image: "mysql:{{ container_tag }}"
docker_network_name: "mysql-tier"
pull: "{%- if MID_INSTALL_SOURCE == 'offline' -%} \
          no \
      {%- else -%} \
          yes \
      {%- endif -%}"
